project_name: localroast
before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: caalberts
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/caalberts/localroast 
  description: Localroast quickly stubs a HTTP server
  test: |
      system "#{bin}/localroast version"

