version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/caalberts/localroast
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/caalberts/localroast
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: make test-cover
      - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN